Refactored shader_factory.cpp into multiple .cpp files This bypasses AppVeyor's `fatal error C1060: compiler is out of heap space`
Alternatively, shaders can be scompiled to binary blobs instead of headers.
On-the-fly CompiledShader construction will, however, be slower so further refactoring will be required (i.e. local to member variables).